# Generated by Django 5.0.4 on 2025-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tutorsession',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutorschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorschedule',
            name='schedule_name',
            field=models.CharField(default='Tutoring Schedule', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tutorsession',
            unique_together={('tutor_schedule', 'date', 'start_time', 'subject')},
        ),
    ]
