# Generated by Django 5.0.4 on 2025-04-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0004_sessionattendance_sessionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrequest',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='SessionAttendance',
        ),
        migrations.DeleteModel(
            name='SessionRequest',
        ),
    ]
