# Generated by Django 5.0.4 on 2025-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0005_remove_sessionrequest_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of the session (optional)', null=True),
        ),
    ]
