# Generated by Django 5.0.4 on 2025-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0007_alter_tutorschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('canceled', 'Canceled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10),
        ),
    ]
