# Generated by Django 5.0.4 on 2025-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0009_rename_time_tutorsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='end_time',
            field=models.TimeField(blank=True, default=None, help_text='End time of the session (auto-calculated if not set)', null=True),
        ),
    ]
