# Generated by Django 5.0.4 on 2025-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0010_tutorsession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorschedule',
            name='completed_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
