# Generated by Django 5.0.4 on 2025-04-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0011_tutorschedule_completed_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorschedule',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance to be paid (total_price - paid_amount)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tutorschedule',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount that has been paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='tutorschedule',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for all sessions in this schedule', max_digits=10),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated price for this session based on duration and subject rate', max_digits=10),
        ),
    ]
