# Generated by Django 5.0.4 on 2025-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0012_tutorschedule_balance_tutorschedule_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorschedule',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount that has been paid (auto-calculated from completed sessions)', max_digits=10),
        ),
    ]
