# Generated by Django 5.0.4 on 2025-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0014_tutorsession_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('canceled', 'Canceled'), ('canceled_by_parent', 'Canceled by Parent'), ('canceled_by_tutor', 'Canceled by Tutor'), ('withdrawn', 'Withdrawn'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
    ]
