# Generated by Django 5.0.4 on 2025-04-28 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0015_alter_tutorsession_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorsession',
            unique_together={('tutor_schedule', 'date', 'start_time', 'subject')},
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours (0.5-8 hours)', max_digits=4),
        ),
        migrations.AddConstraint(
            model_name='tutorschedule',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='tutorschedule',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2025, 4, 28))), name='start_date_not_in_past'),
        ),
        migrations.AddConstraint(
            model_name='tutorschedule',
            constraint=models.CheckConstraint(check=models.Q(('total_hours__lte', 320)), name='max_weekly_hours_320'),
        ),
        migrations.AddConstraint(
            model_name='tutorsession',
            constraint=models.CheckConstraint(check=models.Q(('duration__gte', 0.5), ('duration__lte', 8)), name='valid_session_duration'),
        ),
        migrations.AddConstraint(
            model_name='tutorsession',
            constraint=models.CheckConstraint(check=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('start_time__lt', models.F('end_time')), _connector='OR'), name='valid_time_range'),
        ),
    ]
