# Generated by Django 5.0.4 on 2025-04-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0016_alter_tutorsession_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tutorschedule',
            name='end_date_after_start_date',
        ),
        migrations.RemoveConstraint(
            model_name='tutorschedule',
            name='start_date_not_in_past',
        ),
        migrations.RemoveConstraint(
            model_name='tutorschedule',
            name='max_weekly_hours_320',
        ),
        migrations.RemoveConstraint(
            model_name='tutorsession',
            name='valid_session_duration',
        ),
        migrations.RemoveConstraint(
            model_name='tutorsession',
            name='valid_time_range',
        ),
        migrations.AlterUniqueTogether(
            name='tutorsession',
            unique_together={('tutor_schedule', 'date', 'subject')},
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours (1-3 hours)', max_digits=4),
        ),
    ]
