# Generated by Django 5.0.4 on 2025-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0018_remove_userprofile_address_userprofile_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(default='Zamboanga City', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
