# Generated by Django 5.0.4 on 2025-05-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0020_studentprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorschedule',
            name='schedule_name',
        ),
    ]
