# Generated by Django 5.0.4 on 2025-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0021_remove_tutorschedule_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorschedule',
            name='schedule_name',
            field=models.CharField(default='Tutoring Schedule', max_length=100),
        ),
    ]
