# Generated by Django 5.0.4 on 2025-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria_app', '0023_alter_tutorschedule_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorschedule',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance to be paid (total_price - paid_amount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tutorschedule',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount that has been paid (auto-calculated from completed sessions)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tutorschedule',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for all sessions in this schedule', max_digits=10),
        ),
    ]
